/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MonCompteImport } from './routes/mon-compte'
import { Route as MesEnquetesImport } from './routes/mes-enquetes'
import { Route as AccountImport } from './routes/account'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MonCompteRoute = MonCompteImport.update({
  path: '/mon-compte',
  getParentRoute: () => rootRoute,
} as any)

const MesEnquetesRoute = MesEnquetesImport.update({
  path: '/mes-enquetes',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/mes-enquetes': {
      id: '/mes-enquetes'
      path: '/mes-enquetes'
      fullPath: '/mes-enquetes'
      preLoaderRoute: typeof MesEnquetesImport
      parentRoute: typeof rootRoute
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AccountRoute,
  MesEnquetesRoute,
  MonCompteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account",
        "/mes-enquetes",
        "/mon-compte"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/account": {
      "filePath": "account.tsx"
    },
    "/mes-enquetes": {
      "filePath": "mes-enquetes.tsx"
    },
    "/mon-compte": {
      "filePath": "mon-compte.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
